version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file helloWorldfunction.yaml --s3-bucket lambdatest-pipeline --output-template-file outputHWF.yaml
artifacts:
  type: zip
  files:
    - helloWorldfunction.yaml
    - outputHWF.yaml
